version: "3.8"
services:
    # mysql Database container
    ds-mysql:
        image: mysql:8.0.34
        container_name: ds-mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ds-mysql:/var/lib/mysql
    # phpmyadmin container
    ds-adminer:    
        image: adminer
        container_name: ds-adminer
        ports:      
            - "${ADMINER_PORT}:8080"
    # Symfony apache project container
    ds-app:
        build: ./php
        container_name: ds-app
        restart: unless-stopped
        env_file:
            - ../../.env.local
        working_dir: /var/www/
        volumes: 
            - ../../:/var/www
    ds-web:
        image: nginx:latest
        container_name: ds-web
        restart: unless-stopped
        ports: 
            - ${NGINX_PORT}:80
        volumes:
            - ../../:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        environment:
            - TZ=${TIME_ZONE}
    
volumes:
    ds-mysql:
        driver: local